GENERATED_APP_DIRECTORY = 'generated_app'

SRC = 'src'
MAIN = 'main'

JAVA = 'java'
RESOURCES = 'resources'
WEBAPP = 'webapp'

WEB_INF = 'WEB-INF'
JSP = 'jsp'

GENERATED_ROOT_PACKAGE = 'rs.ftn'

DEFAULT_APP_NAME = 'demo'

BOM_TEMPLATE = 'bom_template'
BASE_REPOSITORY_TEMPLATE = 'base_repository_template'
BASE_REPOSITORY_IMPL_TEMPLATE = 'base_repository_impl_template'
ENTITY_REPOSITORY_TEMPLATE = 'entity_repository_template'
SERVICE_TEMPLATE = 'service_template'
SERVICE_IMPLEMENTATION_TEMPLATE = 'service_implementation_template'
MAIN_TEMPLATE = 'main_template'
POM_TEMPLATE = 'pom_template'
CONTROLLER_TEMPLATE = 'controller_template'
DTO_TEMPLATE = 'dto_template'
CONVERTER_ENTITY_TO_DTO_TEMPLATE = 'converter_entity_to_dto_template'
CONVERTER_DTO_TO_ENTITY_TEMPLATE = 'converter_dto_to_entity_template'
NAVBAR_TEMPLATE = 'navbar_template'
ENTITY_BASE_PAGE_TEMPLATE = 'entity_base_page_template'
FORM_TEMPLATE = 'form_template'
ENTITY_OVERVIEW_TEMPLATE = 'entity_overview_template'
APPLICATION_YML_TEMPLATE = 'application_yml_template'

BOM_TEMPLATE_FILE = 'template/bom.template'
BASE_REPOSITORY_TEMPLATE_FILE = 'template/base_repository.template'
BASE_REPOSITORY_IMPL_TEMPLATE_FILE = 'template/base_repository_impl.template'
ENTITY_REPOSITORY_TEMPLATE_FILE = 'template/entity_repository.template'
SERVICE_TEMPLATE_FILE = 'template/service.template'
SERVICE_IMPLEMENTATION_FILE = 'template/service_implementation.template'
MAIN_TEMPLATE_FILE = 'template/main.template'
POM_TEMPLATE_FILE = 'template/pom.template'
CONTROLLER_TEMPLATE_FILE = 'template/controller.template'
DTO_TEMPLATE_FILE = 'template/dto.template'
CONVERTER_ENTITY_TO_DTO_TEMPLATE_FILE = 'template/converter_entity_to_dto.template'
CONVERTER_DTO_TO_ENTITY_TEMPLATE_FILE = 'template/converter_dto_to_entity.template'
NAVBAR_TEMPLATE_FILE = 'template/jsp/navbar.template'
ENTITY_BASE_PAGE_TEMPLATE_FILE = 'template/jsp/entity_base_page.template'
FORM_TEMPLATE_FILE = 'template/jsp/form.template'
ENTITY_OVERVIEW_TEMPLATE_FILE = 'template/jsp/entity_overview.template'
APPLICATION_YML_TEMPLATE_FILE = 'template/application_yml.template'
